site_name: Django with Garnish Documentation

theme:
  name: 'material'
  features:
    - content.tabs
  palette:
    scheme: 'default'
    primary: 'green'
    accent: '#fcfe8f'    

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
nav:
  - Home: index.md
  - Resources : resources.md
  - How Garnish Works: how_garnish_works.md
  - Image Gallery: image_gallery.md

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.bundle.min.js
