# Generated by Django 5.2.5 on 2025-09-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="alternative_name",
            field=models.CharField(default="Foo", max_length=255),
            preserve_default=False,
        ),
    ]
